#!/usr/bin/env python3
"""
extract-doctests.py - Extract compilable test cases from docs/*.md

Scans every Markdown file under docs/ for fenced code blocks tagged as
positive or negative tests and writes them into:

    tests/doctest-extracted/positive/<source-file>-<n>.cpp
    tests/doctest-extracted/negative/<source-file>-<n>.cpp

Supported fence tags:

    ```cpp positive-test
    // Full .cpp file content — compiled and run; must exit 0.
    ```

    ```cpp negative-test
    // Full .cpp file content — must FAIL to compile.
    // MATCH-ERROR-TEXT: phrases go here as usual
    ```

    ```cpp negative-test match="phrase1|phrase2"
    // Shorthand: match= attribute is injected as MATCH-ERROR-TEXT comments.
    ```

The output directory is wiped and recreated on each run so stale files
don't accumulate.

Usage:
    python tools/extract-doctests.py
    python tools/extract-doctests.py --docs-dir docs/ --out-dir tests/doctest-extracted/
    python tools/extract-doctests.py --dry-run   # print what would be written
"""

import argparse
import os
import re
import shutil
import sys
from pathlib import Path


# Matches opening fence line with test tag.
# Examples:
#   ```cpp positive-test
#   ```c++ negative-test
#   ```cpp negative-test match="cannot convert|no viable conversion"
_FENCE_OPEN = re.compile(
    r'^```(?:cpp|c\+\+)\s+'
    r'(?P<kind>positive|negative)-test'
    r'(?:\s+match="(?P<match>[^"]+)")?'
    r'\s*$'
)

# Matches the closing fence.
_FENCE_CLOSE = re.compile(r'^```\s*$')

# Matches an existing MATCH-ERROR-TEXT comment inside a block.
_MATCH_COMMENT = re.compile(r'//\s*MATCH-ERROR-TEXT:')


def _generated_banner(source_md: Path, block_index: int) -> str:
    return (
        "// AUTO-GENERATED by tools/extract-doctests.py — DO NOT EDIT\n"
        f"// Source: {source_md.name}, block {block_index}\n"
        "//\n"
    )


def extract_from_file(md_path: Path):
    """Yield (kind, lines, match_phrases) for each tagged code block."""
    with open(md_path, encoding='utf-8') as f:
        lines = f.readlines()

    in_block = False
    kind = None
    match_attr = None
    block_lines = []
    block_index = 0

    for line in lines:
        stripped = line.rstrip('\n')

        if not in_block:
            m = _FENCE_OPEN.match(stripped)
            if m:
                in_block = True
                kind = m.group('kind')
                match_attr = m.group('match')  # may be None
                block_lines = []
        else:
            if _FENCE_CLOSE.match(stripped):
                in_block = False
                block_index += 1

                # Collect MATCH-ERROR-TEXT from the block itself.
                inline_phrases = []
                for bl in block_lines:
                    if _MATCH_COMMENT.search(bl):
                        # Already present inline; leave them in the output.
                        inline_phrases.append(bl)

                # Build the phrases list from the match= attribute.
                attr_phrases = []
                if match_attr:
                    for phrase in match_attr.split('|'):
                        phrase = phrase.strip()
                        if phrase:
                            attr_phrases.append(phrase)

                yield kind, block_lines[:], attr_phrases, block_index
            else:
                block_lines.append(line.rstrip('\n'))


def build_output(
    source_md: Path,
    block_index: int,
    kind: str,
    block_lines: list,
    attr_phrases: list,
) -> str:
    """Assemble the .cpp file content for a single extracted block."""
    parts = [_generated_banner(source_md, block_index)]

    # Inject match= attribute as MATCH-ERROR-TEXT comments at the top,
    # only if there are no inline ones already.
    if kind == 'negative' and attr_phrases:
        has_inline = any(_MATCH_COMMENT.search(bl) for bl in block_lines)
        if not has_inline:
            for phrase in attr_phrases:
                parts.append(f"// MATCH-ERROR-TEXT: {phrase}\n")
            parts.append("\n")

    for bl in block_lines:
        parts.append(bl + "\n")

    return "".join(parts)


def run(docs_dir: Path, out_dir: Path, dry_run: bool) -> int:
    """
    Extract all doctests.  Returns the number of files written (or that
    would be written in dry-run mode).
    """
    pos_dir = out_dir / 'positive'
    neg_dir = out_dir / 'negative'

    if not dry_run:
        # Wipe and recreate so stale files don't linger.
        if out_dir.exists():
            shutil.rmtree(out_dir)
        pos_dir.mkdir(parents=True, exist_ok=True)
        neg_dir.mkdir(parents=True, exist_ok=True)

    md_files = sorted(docs_dir.glob('*.md'))
    if not md_files:
        print(f"No .md files found under {docs_dir}", file=sys.stderr)
        return 0

    written = 0
    for md_path in md_files:
        stem = md_path.stem  # e.g. "result", "faq"
        for kind, block_lines, attr_phrases, idx in extract_from_file(md_path):
            filename = f"{stem}-{idx}.cpp"
            dest = (pos_dir if kind == 'positive' else neg_dir) / filename
            content = build_output(md_path, idx, kind, block_lines, attr_phrases)

            if dry_run:
                print(f"[DRY-RUN] Would write {dest}")
                print(content)
                print()
            else:
                dest.write_text(content, encoding='utf-8')
                print(f"  extracted: {dest.relative_to(out_dir.parent)}")

            written += 1

    return written


def main():
    parser = argparse.ArgumentParser(description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        '--docs-dir',
        default=None,
        help='Directory containing .md files (default: docs/ relative to this script)',
    )
    parser.add_argument(
        '--out-dir',
        default=None,
        help='Output root directory (default: tests/doctest-extracted/ relative to this script)',
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Print extracted files without writing them',
    )
    args = parser.parse_args()

    script_dir = Path(__file__).parent.resolve()
    repo_root = script_dir.parent  # tools/ lives one level down from repo root

    docs_dir = Path(args.docs_dir).resolve() if args.docs_dir else repo_root / 'docs'
    out_dir = (
        Path(args.out_dir).resolve()
        if args.out_dir
        else repo_root / 'tests' / 'doctest-extracted'
    )

    if not docs_dir.is_dir():
        print(f"ERROR: docs directory not found: {docs_dir}", file=sys.stderr)
        sys.exit(1)

    print(f"Docs dir    : {docs_dir}")
    print(f"Output dir  : {out_dir}")
    print()

    n = run(docs_dir, out_dir, dry_run=args.dry_run)
    print()
    print(f"{'Would write' if args.dry_run else 'Wrote'} {n} doctest file(s).")
    return 0


if __name__ == '__main__':
    sys.exit(main())
